spring:
  datasource:
    # url: "jdbc:h2:mem:testdb"   --- in memory
    url: "jdbc:h2:file:c:/data/demo"   # file storage
    driverClassName: org.h2.Driver
    username: sa
    password:
  h2:
    console.enabled: true

  jpa:
    show-sql: true
    hibernate.ddl-auto: create-drop
#    hibernate.ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
  sql:
    init:
      mode: always